- name: configure frontend
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    
    - name: enable and start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Remove nginx default content 
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
