- name: configuring mysql database-server
  hosts: db
  become: yes
  become_method: sudo
  become_user: root
  become_flags: '-i'
  tasks:
    # - name: Install MySQL libraries
    #   ansible.builtin.pip:
    #     name: "{{ item }}"
    #     executable: pip3.9
    #   loop:
    #   - cryptography
    #   - PyMySQL

    - name: install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
    
    - name: Starting and enabling MySQL server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: changing root-default password
      ansible.builtin.user:
        name: root
        password: "{{ root_pass | password_hash('ExpenseApp@1') }}"